version: '3'
services:
  db:
    image: mariadb:latest
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=#234@sdfE
      - MYSQL_DATABASE=DbWordPress
      - MYSQL_USER=jonss
      - MYSQL_PASSWORD=mestre123
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    volumes:
      - ./wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=jonss
      - WORDPRESS_DB_PASSWORD=mestre123
      - WORDPRESS_DB_NAME=DbWordPress
  
