name: CI

on:
  push:
    branches: [main]
    
jobs:

  backup_theme_folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
        
      - name: create backup folder
        run: sh desafio-tech/.github/workflows/create-backup-folder.sh
     
      - name: Commit and push backup changes
        run: |
          git config --global user.email "jonathan.soares91@outlook.com" 
          git config --global user.name "jonss" 
          git add -A wordpress_data/wp-content/themes/twentyfifteen_tmp
          git add -A wordpress_data/wp-content/themes/twentyfifteen_old
          git commit -m "Create backup of theme folder" 
          git push origin main
          
          
  deploy_production:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Deploy to production
        env:
          TARGET_BRANCH: prod
        run: |
          echo "Deploying to homologation branch" &&
          git checkout -B $TARGET_BRANCH && 
          if git diff --name-only origin/main; then
          git merge origin/main &&
          git config --global user.email "jonathan.soares91@outlook.com" &&
          git config --global user.name "jonss" &&
          git push --force --set-upstream origin $TARGET_BRANCH
          fi

  deploy_homologation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Deploy to homologation
        env:
          TARGET_BRANCH: homolog
        run: |
          echo "Deploying to homologation branch" &&
          git checkout -B $TARGET_BRANCH &&
          if git diff --name-only origin/main; then
          git merge origin/main && 
          git config --global user.email "jonathan.soares91@outlook.com" &&
          git config --global user.name "jonss" &&
          git push --force --set-upstream origin $TARGET_BRANCH
          fi
