name: CI

on:
  push:
    branches: [main]
    
jobs:

  backup_theme_folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create backup folder
        run: |
          mkdir -p wordpress_data/wp-content/themes/twentyfifteen_tmp &&
          mkdir -p wordpress_data/wp-content/themes/twentyfifteen_old &&
          cp -R wordpress_data/wp-content/themes/twentyfifteen wordpress_data/wp-content/themes/twentyfifteen_old
          rsync wordpress_data/wp-content/themes/twentyfifteen wordpress_data/wp-content/themes/twentyfifteen_old && 
          cp -R wordpress_data/wp-content/themes/twentyfifteen_tmp wordpress_data/wp-content/themes/twentyfifteen

      - name: Commit and push backup changes
        run: |
          git config --global user.email "jonathan.soares91@outlook.com" &&
          git config --global user.name "jonss" &&
          git add wordpress_data/wp-content/themes/twentyfifteen_old &&
          git commit -m "Create backup of theme folder" &&
          git push origin main
          
  deploy_production:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Deploy to production
        env:
          TARGET_BRANCH: produção
        run: |
          echo "Deploying to production branch" &&
          git fetch origin main &&
          if git diff --name-only origin/main; then
            git checkout $TARGET_BRANCH &&
            git merge origin/main &&
            git config --global user.email "jonathan.soares91@outlook.com" &&
            git config --global user.name "jonss" &&
            git push --set-upstream origin $TARGET_BRANCH
          else
            echo "No changes to deploy."
          fi


  deploy_homologation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Deploy to homologation
        env:
          TARGET_BRANCH: homologação
        run: |
          echo "Deploying to homologation branch" &&
          git fetch origin main &&
          if git diff --name-only origin/main; then
            git checkout $TARGET_BRANCH &&
            git merge origin/main &&
            git config --global user.email "jonathan.soares91@outlook.com" &&
            git config --global user.name "jonss" &&
            git push --set-upstream origin $TARGET_BRANCH
          else
            echo "No changes to deploy."
          fi
